-- AddressChanges table
CREATE TABLE Searches
(
	ID					INT IDENTITY (1,1) NOT NULL,
	QUERY				NVARCHAR(100) NULL,
	IP_ADDRESS			NVARCHAR(100) NULL,
	USERAGENT			NVARCHAR(100) NULL,
	SEARCH_DATE			DATETIME NOT NULL,
	
	CONSTRAINT [PK_dbo.Searches] PRIMARY KEY CLUSTERED (ID ASC)
);

SELECT * FROM Searches;